# Generated by Django 4.1.3 on 2022-12-05 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor_selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Section_ID', models.CharField(max_length=150)),
                ('Category', models.CharField(choices=[('Project', 'Project'), ('Thesis', 'Thesis'), ('Research', 'Research')], max_length=50, null=True)),
                ('Working_Area', models.CharField(choices=[('AI', 'AI'), ('Machine Learning', 'Machine Learning'), ('Deep Learning', 'Deep Learning')], max_length=50, null=True)),
                ('Select_Teacher', models.CharField(max_length=100)),
                ('Objective', models.CharField(max_length=150)),
                ('Motivation', models.CharField(max_length=150)),
                ('Expected_Outcome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='S_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_term', models.CharField(choices=[('LEVEL-4 TERM-1', 'LEVEL-4 TERM-1'), ('LEVEL-4 TERM-2', 'LEVEL-4 TERM-2')], max_length=50, null=True)),
                ('identity', models.CharField(max_length=30)),
                ('batch', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=14)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
